carpedm20/awesome-hacking

- README.md
Added just a new game for "web hacking"
> What's 0xf.at?
> 0xf.at (or oxfat it you prefer) is a website without logins or ads where you can solve password-riddles (so called hackits).
> Add wargame-web "0xfat"

- README.md
The initial link ( https://github.com/josephmisiti/awesome-machine-learning/blob/master/books.md ) is actually books based on machine learning and doesn't have security and hacking related books. The new link has a lot of computer security ebooks which are free for anyone to download. The list will also be updated regularly.
> Updated link to free hacking and security ebooks.

- README.md
> Added NodeGoat docker link and directions.

- README.md
see https://www.owasp.org/index.php/OWASP_Juice_Shop_Project
> Add OWASP Juice Shop to pentest Docker images

- README.md
Hi,
Thank you for your job.
I cleaned up the table of contents and fixed some broken links.
Thank you!
> Clean up table of contents and links

- README.md
> A curated list of movies every hacker & cyberpunk must watch.
**GitHub Repo: [here](https://github.com/k4m4/movies-for-hackers)**
> Add Movies For Hackers (to General)

- README.md
Amass is the most effective open source subdomain enumeration tool available
https://github.com/caffix/amass
Thanks!
> Add Amass to the Network Tools Section

- README.md
Hey guys, links were not working properly in the table of contents, so I fixed them.
Also removed links that were pointing on nothing.
> Fixed links in the README

- README.md
Added:
* VHostScan
* Subfinder
* NoSQLMap
> Update tools listings

- README.md
Also added a General subsection to keep the consistency.
> Add Strong node.js (to Web)

- README.md
Contains a tools section with empire and silent trinity
> Added a post exploitation section

- README.md
* Added some tools.
* Added some sections.
* Moved some tools into another section.
> Some fixes.

- README.md
added findsubdomains, cirt-fuzzer and aslookup
> add a few tools

- README.md
This is a wargame site by the biggest Austrian CTF team "LosFuzzys". They upload challenges they encountered in actual CTFs, or self written ones. There are lots of easy one, and lots of hard ones. It's mainly web, but also lots of reverse-engineering, bin-exploit etc.
> Added fuzzy.land to web-wargames

- README.md
added some cool tools that should be there IMHO
> added findsubdomains and spyse

- README.md
https://github.com/RustScan/RustScan
https://github.com/Ciphey/Ciphey
> Added Ciphey & RustScan

- README.md
Removing Link for Lena RE Resource that doesn't exist. Added Begin RE resource that loads properly. Added Malwareunicorn's RE Tutorial.
> Lena's RE Tutorial Link Doesn't exit

- README.md
Updates link to use official metasploit docker image
Addresses first part of #37
> Updates Docker Metasploit

- README.md
Adds Ghidra to list of Reverse Engineering Disassemblers and debuggers
> Adds Ghidra

- README.md
**docker pull kalilinux/kali-linux-docker** URL is incorrect or not updated
> update url of "docker pull kalilinux/kali-linux-docker"

- README.md
Added Shodan and Masscan which are excellent at OSINT and scanning. Masscan is similar to nmap, but is much quicker. I also added CyLR which is a great forensic imager.
> Added to Web and Forensic Tools
